### ISSUE TITLE
[r] Create tickets for R API gaps

### ISSUE THREAD

**Issue by pablo-gar** [single-cell-data/TileDB-SOMA#1126]
In an attempt to identify our work required to cut an RC for the R API I did re-audit based on #839.

## Re-audit

Notes:
* All "Needs to take platform_config [...]" items were intended to be addressed in #735; but the PR associated to that issue (#1026) only created the classes `platform_config` and `SOMATileDBContext`, in many cases they still need to be supported as arguments in many `create`/`write` methods

* Foundational types
  * `SOMADataFrame`
    * [ ] `create`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L44), [R](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a10/apis/r/R/SOMADataFrame.R#L23)
      * Needs to take args for `platform_config` and `context`. **The classes were implemented but it is still not supported as an argument** #1151
    * [ ] `read`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L59), [R](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a10/apis/r/R/SOMADataFrame.R#L156)
      * Needs full argument support 
    * [ ] `write`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L77), [R](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a10/apis/r/R/SOMADataFrame.R#L117)
      * [ ] Needs `platform_config` support **The classes were implemented but it is still not supported as an argument** #1151
  * `SOMASparseNDArray`
    * `create`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L117), [R](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a10/apis/r/R/SOMASparseNdArray.R#L33)
      * [ ] Needs to take args for `platform_config` and `context`  **The classes were implemented but it is still not supported as an argument** #1151
      * [ ] Needs factory-method approach #1008
    * [ ] `read`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L207), [R `read_arrow_table`](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a10/apis/r/R/SOMASparseNdArray.R#L94), [R `read_sparse_matrix`](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a10/apis/r/R/SOMASparseNdArray.R#L150)
      * Needs `batch_size` and `partitions` #1005
  * `SOMADenseNDArray`
    * `read`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L160), [R `read_arrow_table`](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a10/apis/r/R/SOMADenseNdArray.R#L93), [R `read_dense_matrix`](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a10/apis/r/R/SOMADenseNdArray.R#L149)
      * [ ] Needs `platform_config`, `partitions`, `result_order` **The classes were implemented but it is still not supported as an argument** #1151
    * `write`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L176), [R](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a10/apis/r/R/SOMADenseNdArray.R#L188)
      * Needs to take `platform_config` **The classes were implemented but it is still not supported as an argument** #1151
* Composed types
  * Shared code
    * [x] `create`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/collection.py#L31), [R](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a10/apis/r/R/SOMACollectionBase.R#L21) -- needs factory-method approach #1008
    * [x] `open`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/base.py#L24), [R](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a10/apis/r/R/TileDBArray.R#L81) -- needs factory-method approach #1008
    * [x] `close`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/base.py#L77), [R] needs to be public: #1010
    * [ ] `context` accessor: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/base.py#L42), [R] #1011, with #735 as prerequisite
  * `SOMAExperiment`
    * [x] Class: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/experiment.py), [R](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a10/apis/r/R/SOMAExperiment.R)
      * Full parity except for `axis_query`
      * [ ] [R] Use `Futures` library to accelerate #943
  * Ephemeral -- more analysis pending until R's `ExperimentQuery` is merged
    * [ ] `uri`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/ephemeral/collections.py#L37), [R] #1022
    * [ ] `metadata`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/ephemeral/collections.py#L41), [R] #1022
    * [ ] `open`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/ephemeral/collections.py#L45), [R] #1022
    * [ ] `create`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/ephemeral/collections.py#L52), [R] #1022
    * [ ] `set`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/ephemeral/collections.py#L70), [R] #1022
* Options
  * [ ] Class: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/options.py), [R] #1183
* Others
  * [ ] `coos`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L287), [R] #1007
  * [ ] `dense_tensors`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L296), [R] #1007
  * [ ] `record_batches`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L298), [R] #1007
  * [ ] `tables`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L301), [R] #1007
* To/from Seurat matching Python's [`soma.io`](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a11/apis/python/src/tiledbsoma/io/ingest.py)
  * `to_seurat` #941 
  * `from_seurat` #941

**Comment by johnkerl** [comment]
Created #1151 which handles all `[needs ticket]` but one.

**Comment by johnkerl** [comment]
Everything with `[needs ticket]` has had a ticket created -- closing this issue.
