### ISSUE TITLE
Progress tracker

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#113]
# Context

End-to-end functioning of the API for the May-June timeframe.

# Higher-level goals

- [X] SOMA-read and schema-introspection APIs
  - [X] Need to be able to introspect schema on `obs`, `var`, `X`, `uns`, and `obsm`: 
    * #94
    * #97
    * #104
    * #125
  - [X] Need to be able to slice/read the same
    * #102
    * #103
    * see also issue #95
  - [X] `apis/python/examples/` directory, moving toward vignette-style deliverable
    * #136
  - [X] Refactoring of `README` content:
    * #122
- [ ] More on SOMA-read and schema-introspection APIs
  - [ ] Possible work integrating metadata hints/labels from the I/O routines: e.g., embedding discovery, X scale, etc.
  - [ ] Provenance hints on various SOMA slots ("this came from a `numpy.ndarray`" etc.) and readback-as-such support
- [X] Resolve AnnData ingestion issues:
  - [X] #71
    * #115
  - [X] Chunked reads for CSC and dense (in addition to CSR)
    * #37
    * #120
    * Note, global-order-write feature to avoid need for consolidation is still open / pending `TileDB-Py`
- [ ] SOMA API: support for incremental queries when used to map/reduce X/raw.X (à la `TileDB.query(return_incomplete=True))`, with performance essentially the same as from native TileDB
- [X] I/O namespace:  move IO API into the `tiledbsc.io` namespace
  * #83
- [ ] I/O: resolve any logical data organizational changes from spec edits
  - [ ] Python/R raw status
  - [X] Impl: programmable X layer: `X["data"]` not `X.data`, and ability to add others
    - #142
- [X] Multimodal data: gap analysis with respect to current SOMA/SOCO API
  - This is addressed in the next-generation data model https://github.com/single-cell-data/SOMA/blob/spec-revision/brainstorming.md
- [ ] SOMA-collection steps:
  - [X] Populate a SOMA collection:
    * #118
    * #136 (examples)
    * #173
    * #161
  - [X] Batch-process, e.g. mean of `raw/X/data` grouping by `obs['cell_type_ontology_term_id']`
    - #173
  - [ ] Random sampling
  - [X] Slice-creation: filter on values in specified `obs`/`var`, create `AnnData` object, store at `.h5ad`
    * #173
  - [X] Add/delete SOMAs to/from the collection
  - [ ] Synchronize API-spec edits and make sure demo material uses only the documented SOMA API
- [X] Documentation
  - [X] Have Python-API online help clearly navigable: what methods are available for which SOMA slots
  - [X] Have Python-API docs accessible on the web
    - [https://tiledb-singlecell-docs.s3.amazonaws.com/docs/overview.html](https://tiledb-singlecell-docs.s3.amazonaws.com/docs/overview.html)
[X] Storage support:
  - [X] Local disk
  - [X] `s3://...` supported by `tiledbsc-r` and `tiledbsc-py`
    * Examples on #148
    * Timings look good when queried from `m6i.4xlarge` in the same S3 region as the storage, as well as from TileDB Cloud notebooks
  - [X] `tiledb://...` supported by `tiledbsc-r` and `tiledbsc-py`
    - #189
- [ ] Proposal/demo of SOCO-level query acceleration on large-scale collections
  - [X] Loop over collections: #118
  - [ ] Possible addition of a sparse-array index layer
  - [ ] Possible consolidating-write approach
- [ ] More SOMA-collection steps:
  - [X] WIP: Larger datasets and query timings
  - [ ] Collection-rebuild timings
  - [ ] Larger-scale map-reduce timings
  - [ ] Larger-scale random sampling

# Performance/scale:
- [X] X `obs_id` filter RLE vs zstd
- [ ] Global-order writes in `TileDB-Py` #37
  - [ ] Needs exposure of global-order-write flag to Python API -- TileDB Shortcut task 17495
  - [ ] Prep-sort work within `tiledbsc-py` -- be sure to column-sort data going in to the chunk writes
  - [ ] Re-ingest datasets
- [ ] Column-major storage: [TileDB-Py #3143](https://github.com/TileDB-Inc/TileDB/pull/3143) -- performance-tuning level
- [ ] Apply dictionary encoding #36

# TileDB-API support

- [X] TileDB attributes can be UTF-8, but, are not queryable if they are -- so we must store them as ASCII. In this package, make sure queries read back with decode (`"MT-CO3"` not `b"MT-CO3"`):
  * #101
  * #117
  * #138 
  * #141
- [X] Exposure of global-order-write flag to Python API -- TileDB Shortcut task 17495 -- see also "Performance/scale" above -- without this, column-level queries [maybe be slow](https://github.com/single-cell-data/TileDB-SingleCell/blob/main/apis/python/README-csr-ingest.md) which we need to solve for GA -- update 2022-06-06: query performance is not negatively impacted on local disk or S3 by the existence of unconsolidated chunks
- Query syntax:
  - [X] `and` -- in place
  - [X] `or` -- like `obs.cell_type == "blood" or obs.cell_type == "lung"` -- as of [0.0.5](https://github.com/single-cell-data/TileDB-SingleCell/releases/tag/0.0.5)
  - [ ] `in` -- like `obs.cell_type in ["blood", "lung"]` -- WIP -- TileDB Shortcut story 19015
- [X] Empty-string writes
  - [X] Pending [TileDB-Py #1089](https://github.com/TileDB-Inc/TileDB-Py/pull/1089)
  - [X] But, that can be avoided in this package by writing scalar uns values as group metadata rather than 1D arrays -- which is in turn blocked by:
    - [X] Group-metadata discovery
      - TileDB Shortcut story 17879 and [TileDB-Py PR 1123](https://github.com/TileDB-Inc/TileDB-Py/pull/1123)
      - #144
- [X] `"name" in G`: TileDB Shortcut story 18057 -- non-blocking; will simplify some code in this package
  - [TileDB-Py PR 1125](https://github.com/TileDB-Inc/TileDB-Py/pull/1125)
- [ ] Reversible typecasts #106
  - [X] `TILEDB_BOOL` TileDB Shortcut story 17783 -- released in `tiledbsc-py` [0.0.6](https://github.com/single-cell-data/TileDB-SingleCell/releases/tag/0.0.6)
  - [ ] In this package, save array metadata like "was CSR", etc., along with language/version of the code that wrote the data (`tiledbsc-r` / `tiledbsc-py`)
- [X] `tiledb.from_numpy` (for `uns`) overwrite/append flag: TileDB Shortcut story 17765 -- important for S3/TileDB-Cloud ops
- [ ] `tiledb.from_numpy` (for `uns`): 1D arrays are not uploadable.
  - https://github.com/single-cell-data/TileDB-SingleCell/pull/201 workaround
  - TileDB Shortcut story 19039 filed

**Comment by johnkerl** [comment]
This tracked issues for the May/June timeframe. I'll open a new one for current cross-company issue-tracking.
