### ISSUE TITLE
[c++] Sequencing/umbrella for C++ work

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#1240]
**Pre-coding tasks**

* Fold in the output of #1239 
* Enumerate whatever's not already OK with #922 
* Close out #922 
* Replace it with a new write-up

---
**Set up new directory structure**

- [x] #1300

**Create internal use classes**

- `SOMAArray`
    - [x] #1282
    - [x] Metadata functions https://github.com/single-cell-data/TileDB-SOMA/issues/926: First pass places metadata values into `void*` buffer
      - [x] #1577
      - [ ]  Second pass to return as `SOMAMetadataMapping` where underlying data structure is an `arrow::Table`
    - [x] `schema`: First pass will use the already existing `ArraySchema SOMAArrayReader::schema()`
      - [ ] Additional pass to return `arrow::schema` https://github.com/single-cell-data/TileDB-SOMA/issues/1121
    - [x] `read_next`: First pass will return data as `ArrayBuffers` (already implemented)
      - [ ] Additional pass to return `arrow::RecordBatch` or `arrow::Table`
    - [x] `write`: First pass #1364
      - [ ] Additional pass to add batching and parallization optimizations https://github.com/single-cell-data/TileDB-SOMA/issues/1175#issuecomment-1502277218
      - [ ] Additional pass to take data in the form of `arrow::RecordBatch` or `arrow::Table`
- `SOMAGroup`  
  - [x] `open`
  - [x] `close`
  - [x] Metadata functions #1247 
      - [x] #1577
      - [ ] #1351
  - [x] Group member functions https://github.com/single-cell-data/TileDB-SOMA/issues/1248
  - [x] `member_to_uri_mapping` https://github.com/single-cell-data/TileDB-SOMA/issues/1122'      
      - [x] #1623
      
**Create public API**

- [x] #1356
- [x] #1256
- [x] #1354
- [x] #1355
- [x] #1257
- [x] #1258
- [x] #1575

**Replace API bindings**

- [ ] #1632
- [ ] Replace TileDB-SOMA-R bindings

**Comment by johnkerl** [comment]
> @github-project-automation github-project-automation bot moved this from In Progress to Done in Sprint tracking yesterday

Not desired.

**Comment by johnkerl** [comment]
This needs to remain open until all items are checked off with PRs merged into `main`.

**Comment by johnkerl** [comment]
The only remaining item is #1632 which is open. No remaining reason to leave this one open.
