### ISSUE TITLE
[r] sr_setup must have the same arguments as soma_array_reader

### ISSUE THREAD

**Issue by pablo-gar** [single-cell-data/TileDB-SOMA#1421]
`sr_setup` is missing essential args, for example `result_order`

**TODO**
- [ ] complete `sr_setup` to match `soma_array_reader args`
- [ ] add `result_order` arg to `SOMASparseNDArray$read()`
- [ ] Bring these tests back https://github.com/single-cell-data/TileDB-SOMA/blob/ebce684b27eb1090d9fa63e742305d1518194256/apis/r/tests/testthat/test-SOMASparseNDArray.R#L17
