### ISSUE TITLE
[r/python] Parent/tracking issue for shape

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#1445]
## Factors

**There are two possible meanings of shape:**

* Bounding box for the data that are currently in a sparse array
* Capacity or domain, i.e. the bounds outside of which no data are allowed to be written

There exist software systems where "shape" takes the former meaning, and software systems where "shape" takes the latter meaning. For SOMA, shape takes the latter meaning.

People need to be able to access both of these values for all the arrays within a SOMA experiment. For systems in which "shape" takes the former meaning, accessors might be called "shape" and "maxshape", respectively. For SOMA, where "shape" takes the latter meaning, accessors are non-empty domain and "shape", respectively.

For the TileDB implementation of SOMA, note that domains are fixed at array-creation time; an array cannot have its domain enlarged post-create.

**Non-append and append modes:**

There is an important single-cell use-case in which users have some amount of data in a SOMA experiment, then add or append more data later -- for example, appending the results of the next day's laboratory run. Users don't know, and can't know, the final dimensions of their data at array-creation time; there must be room for growth.

There is another use-case, the "immutable" mode, in which some number of inputs are used to create a timestamped SOMA experiment. When later data arrive, and entirely new experiment is written. This design pattern is used, for example, by the CZ CELLxGENE Discover Census.

**R 31-bit issues:**

There are container classes in which the shape-as-capacity of a sparse array -- even one with a very small number of occupied datapoints -- must not exceed 2**31-1. This is an important interoperability issue for the room-for-growth use-case: experiments written by Python, with room-for-growth shape, should still be readable by R software without signed-int32-overflow issues.

Even when array shapes do not exceed 2**31-1, R software can abort with cholmod errors trying to read a sparse array (even with the number of occupied cells is quite small).

## Things to be done

* [x] Documentation for the R and Python packages need to be clear, for each foundational class, that "shape" means _the domain outside of which no data can be written_: #1446.
* [ ] The sparse n-d array class, in R and Python both, needs support for non-empty-domain read access.
  * We will use TileDB array metadata to track this.
  * @mojaveazure has an open design document on this
  * (Note that the TileDB-level `nonempty_domain` accessor isn't quite what we need. Example: a sparse array which is thought of as 100x200 (100 cells, 200 genes). If the array is densely occupied then the TileDB non-empty domain is ((0,99),(0,199)). But if the array is sparsely occupied, with leading/trailing rows/columns empty, then the TileDB non-empty domain may be, say, ((2,97),(3,194)) or what have you.)
  * (Note that array-external numbers like nobs and nvar don't always suffice either. For `X`, they do, but for the second dimension of `obsm` and `varm`, we need a way to track the intended bounds.)
  * This may impact #1434.
* Default shapes for R and Python in the from-anndata / from-seurat / from-sce modules must be the same:
  * [X] Option: have shape dimensions default to 2^31-1 -- which is a room-for-growth parameterization. See #1440.
  * Option: have shape dimensions default to tight-fit (e.g. 100x200) _unless_ the experiment is explicitly ingested with an appendable flag
  * Option: force every experiment array to have its shape specified
    * Risk of parameter explosion: any SOMA experiment can have `X` matrices (nominally nobs x nvar), `obsm` matrices (nominally nobs x varying), `obsp` matrices (nominally nobs x nobs), `varm` (nominally nvar x varying), and `varp` (nominally nvar x nvar). We would need a user-level parameterization syntax wherein they specify the shapes of all matrices in the to-be-ingested experiment. See https://github.com/single-cell-data/TileDB-SOMA/pull/1440#issuecomment-1578773781 for specifics of the parameter-explosion problem.
* Interoperability:
  * Experiments written by Python with room-for-growth shape:
    * [X] Need to be readable by R software -- see also #1348
    * [ ] Need to be able to be exported to Seurat and SCE format -- see also #1424 and #1279
  * Experiments written by R with room-for-growth shape:
    * [ ] Need to be readable by Python software #1278
    * [ ] Need to be exportable to AnnData format #1278

**Comment by pablo-gar** [comment]
@johnkerl, @aaronwolen, and @mojaveazure and I are aligned on that the work required for the bounding-box issue (and its suggested solution of encoding `used_shape` as metadata) should not be a blocker for the 1.0 release.

All **internal** blocking uses cases have been addressed by #1478 

cc @bkmartinjr

**Comment by pablo-gar** [comment]
@aaronwolen upon merging https://github.com/single-cell-data/TileDB-SOMA/pull/1504 is it safe to remove the `1.0rc-r` label?

**Comment by johnkerl** [comment]
All remaining work has had separate tracking issues tasked out. Closing this issue.

**Comment by johnkerl** [comment]
See also #2407
