### ISSUE TITLE
[r] Prepare for TileDB-SOMA R GA

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#1567]
## ​​Prerequsites

- [X] ​​Obtain CZI sign-off on proceeding with R general availability release

## ​​Dependencies

* ​​TileDB core 2.16.1
  - [X] ​​Release tag and GitHub artifacts https://github.com/TileDB-Inc/TileDB/releases/tag/2.16.1 — note 2.16.1 has a bugfix which is a release-blocker for TileDB-SOMA R GA
* ​​TileDB-Py 0.22.1
  - [X] ​​Release tag and GitHub artifacts https://github.com/TileDB-Inc/TileDB-Py/releases/tag/0.22.1
  - [X] ​​Artifacts on PyPI [https://pypi.org/project/tiledb/](https://pypi.org/project/tiledb/#history)[#history](https://pypi.org/project/tiledb/#history)
* ​​TileDB-R 0.20.2
  - [X] Release tag and GitHub artifacts https://github.com/TileDB-Inc/TileDB-R/releases/tag/0.20.2
  - [X] Artifacts available on r-universe https://tiledb-inc.r-universe.dev/tiledb -- artifacts not yet available on CRAN as we are one week into a two-week CRAN organizational break that ends August 7th

## ​​Release Preparation

- [X] ​​Merge https://github.com/single-cell-data/TileDB-SOMA/tree/aaronwolen/docs-cleanup to reduce cross-section of exported namespace
- [X] Temporarily change r-universe build cadence to release-only so users can obtain 0.22.1 builds from there until the update is available on CRAN https://github.com/TileDB-Inc/tiledb-inc.r-universe.dev/pull/2
- [X] ​​Depend on  2.16.1, 0.22.1, and 0.20.2 in Python, R, and C++ dependency files: https://github.com/single-cell-data/TileDB-SOMA/pull/1561
- [X] ​​Update CI to install tiledb-r​ from R-universe due to the CRAN hiatus noted above
  - [X] Step 1: https://github.com/TileDB-Inc/tiledb-inc.r-universe.dev/pull/2
  - [X] Step 2: https://github.com/single-cell-data/TileDB-SOMA/pull/1570
- [X] ​​Regenerate docs
- [X] Verify no errors in `R CMD check` locally, and submit to rhub
    - Verifies that builds succeed in different CRAN-like environments — this is an efficient way to test/safety-check the package on a variety environments
- [X] Revert https://github.com/TileDB-Inc/tiledb-inc.r-universe.dev/pull/3
- [X] ​​Release PR #1574 for `tiledbsoma-r​`
  - [X] ​​Update Version​ field in DESCRIPTION​ file to 1.4.0​
  - [X] ​​Update top header in NEWS.md​ file to # TileDB-SOMA 1.4.0​
- [X] https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases including but not limited to the following:
  - [X] Create release branch `release-1.4` from `main` on `single-cell-data/TileDB-SOMA`
  - [X] Absolute necessity to do the Conda pre-check step shown in that wiki before tagging `1.4.0` in `single-cell-data/TileDB-SOMA`
  - [X] Tag `1.4.0` in `single-cell-data/TileDB-SOMA`

### Dependencies

- [x] tiledb​ 2.16.1 available on conda-forge anaconda channel (https://anaconda.org/conda-forge/tiledb/labels)
- [x] ​​tiledb-py​ 0.22.1 available on conda-forge anaconda channel (https://anaconda.org/conda-forge/tiledb-py/labels)
- [x] ​​r-tiledb​ 0.20.2 available on conda-forge anaconda channel (https://anaconda.org/conda-forge/r-tiledb/labels)

### ​​Update steps
​​
- [X] Create PR to update `tiledbsoma-feedstock​` https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/39
  - [X] ​​Update `version​/version_r`​ fields in `recipe/meta.yaml`​ to 1.4.0
​​
## Validation

- [X] `​​tiledbsoma​` 1.4.0 available on conda-forge anaconda channel
  - [X] ​​https://anaconda.org/tiledb/libtiledbsoma/labels
  - [X] ​​https://anaconda.org/tiledb/tiledbsoma-py/labels
  - [X] ​​https://anaconda.org/tiledb/r-tiledbsoma/labels
​​
## TileDB Cloud Updates

Internal

## CRAN submission, which will be 1.4.1

- [ ] ​​Add/update CRAN comments -- tracked in #1582
- [ ] ​​Submit to R-hub builder and verify no errors (prep for release to CRAN, not a GA blocker) -- tracked in #1582

**Comment by johnkerl** [comment]
CRAN items (1.4.1) split out on #1582
