### ISSUE TITLE
[r] Prepare for CRAN [long-term tracker]

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#1582]
Follow-on from #1567 

- [ ] ​​Add/update CRAN comments (this is not an actual requirement at CRAN)
- [ ] ​​Submit to R-hub builder and verify no errors (prep for release to CRAN, not a GA blocker) (R-hub may fail due to our build process, is also challenged by our long list of dependencies, first attempt just failed for DE)
- [ ] Audit relative to the one authorative manual [Writing R Extensions](https://cran.r-project.org/doc/manuals/R-exts.html) (with [nicer rendering here](https://rstudio.github.io/r-manuals/r-exts/))
- [ ] Audit relative to [CRAN Repository Policy](https://cran.r-project.org/web/packages/policies.html) document
- [ ] Change build process to not require download at build time, need to vendor in capnp and spdlog, see [CRAN Repository Policy 'External Libries'](https://cran.r-project.org/web/packages/external_libs.html) and ['Using Rust'](https://cran.r-project.org/web/packages/using_rust.html) along with (on email list) preference for 'vendored' over downloaded (this may be a "maybe" as a) use system libs first and b) can ask for forgiveness here)
- [ ] Pass `R CMD check --as-cran` on r-release as a minimal layer
- [ ] Pass `R CMD check --as-cran` on r-devel (in docker, locally [ I keep it on Ubuntu ], rhub, ~win-builder~ (inapplicable, no Windows package), mac-builder (works, has cnake and git)
- [ ] Pass `R CMD check --use-valgrind` (and inspect `*.Rout` files created) which currently errors and would lead to CRAN removal post-acceptance
- [ ] Pass all the "informal checks" the "new package submission desk" runs on eg authors, credits, references, ...
- [ ] Utilise experience of at least three contributors with active CRAN packages
- [ ] Update our [release procedure](https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases) to reflect publishing to CRAN
- [ ] Update the user-facing readme/docs to refer to CRAN instead of r-universe

**Comment by eddelbuettel** [comment]
In my experience the CRAN_comments.md is a myth.  I have never heard _anyone from CRAN recommending or requesting it_ yet I heard repeatedly that whatever was written is a myth.

**Comment by johnkerl** [comment]
@eddelbuettel what steps remain to bring this issue to closure?

**Comment by eddelbuettel** [comment]
There was a bit of a sentiment recently that maybe CRAN release does not buy as all that that we don't already have with r-universe.  Happy to chat off-line.

**Comment by johnkerl** [comment]
Per internal discussion we will revisit this once TileDB-R has been removed as a dependency from TileDB-SOMA-R. See also #2406.
