### ISSUE TITLE
[python] `tiledbsoma.io.update_uns` (parent issue)

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#2707]
Sequencing:

* [ ] v1: will add items, present in the new `adata.uns`, not present at all in the existing `exp.uns`
* [ ] v2: will delete items, not present in the new `adata.uns`, present at all in the existing `exp.uns`
* [ ] v3: items present in both: same schema, allow replacement if same shape
* [ ] v4: items present in both: same schema, allow replacement if bigger shape (will require core shape support, probably 2.25)
* [ ] v5: items present in both: different schema, allow add/drop of columns with no type changes
* [ ] v6: items present in both: different schema, allow add/drop of columns with type changes
  * Note: also affects `tiledbsoma.io.update_obs` and `tiledbsoma.io.update_var`
