### ISSUE TITLE
[r/python] R/Python feature-gap analysis (high-level/parent issue)

### ISSUE THREAD

**Issue by maniarathi** [single-cell-data/TileDB-SOMA#839]
Analyze the Python and R `tiledbsoma` packages to ensure that the APIs are at parity and document any gaps. 

-------------------------

* Foundational types
  * `SOMADataFrame`
    * [ ] `create`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L44), [R](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a10/apis/r/R/SOMADataFrame.R#L23)
      * Needs to take args for `platform_config` and `context` #735
    * [ ] `read`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L59), [R](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a10/apis/r/R/SOMADataFrame.R#L156)
      * Needs full argument support #735
    * [ ] `write`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L77), [R](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a10/apis/r/R/SOMADataFrame.R#L117)
      * [ ] Needs `platform_config` support #735
      * [x] Only supports Arrow `Table` while Python supports Arrow `RecordBatch` or `Table` #939
    * [x] `schema`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L93), [R](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a10/apis/r/R/TileDBArray.R#L81) #978
    * [ ] `index_column_names` accessor: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L99), [R] -- #1006
  * `SOMASparseNDArray`
    * `create`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L117), [R](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a10/apis/r/R/SOMASparseNdArray.R#L33)
      * [ ] Needs to take args for `platform_config` and `context` #735 
      * [ ] Needs factory-method approach #1008
    * [ ] `read`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L207), [R `read_arrow_table`](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a10/apis/r/R/SOMASparseNdArray.R#L94), [R `read_sparse_matrix`](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a10/apis/r/R/SOMASparseNdArray.R#L150)
      * Needs `batch_size` and `partitions` #1005
    * [x] `shape`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L133), [R] ... #940
    * [x] `nnz`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L243), [R] ...  #940
    * [x] `ndim`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L138), [R] ...  #940
    * [x] `schema`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L207), [R] #978
    * [x] `write`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L230), [R](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a10/apis/r/R/SOMASparseNdArray.R#L189): `data` argument should be `values` #1004
  * `SOMADenseNDArray`
    * [ ] `read`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L160), [R `read_arrow_table`](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a10/apis/r/R/SOMADenseNdArray.R#L93), [R `read_dense_matrix`](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a10/apis/r/R/SOMADenseNdArray.R#L149)
      * [ ] Needs `platform_config`, `partitions`, `result_order` #735
    * [x] `shape`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L133), [R] ...  #940
    * [x] `ndim`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L138), [R] ...  #940
    * [x] `schema`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L144), [R] #978
    * [ ] `write`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L176), [R](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a10/apis/r/R/SOMADenseNdArray.R#L188)
      * Needs to take `platform_config` #735
* Composed types
  * Shared code
    * [ ] `create`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/collection.py#L31), [R](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a10/apis/r/R/SOMACollectionBase.R#L21) -- needs factory-method approach #1008
    * [ ] `open`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/base.py#L24), [R](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a10/apis/r/R/TileDBArray.R#L81) -- needs factory-method approach #1008
    * [ ] `close`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/base.py#L77), [R] needs to be public: #1010
    * [ ] `context` accessor: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/base.py#L42), [R] #1011, with #735 as prerequisite
    * [x] `uri` accessor: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/base.py#L37), [R](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a10/apis/r/R/TileDBObject.R#L61)
    * [x] `metadata` accessor: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/base.py#L57); [R arrays](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a10/apis/r/R/TileDBArray.R#L44), [R groups](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a10/apis/r/R/TileDBGroup.R#L137)
  * `SOMACollection`
    * [ ] `add_new_collection`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/collection.py#L75), [R] ... #938
    * [ ] `add_new_dataframe`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/collection.py#L124), [R] ... #938
    * [ ] `add_new_dense_ndarray`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/collection.py#L141), [R] ... #938
    * [ ] `add_new_sparse_ndarray`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/collection.py#L158), [R] ... #938
    * [x] `set` mutator: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/collection.py#L180), [R](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a10/apis/r/R/TileDBGroup.R#L34)
  * `SOMAExperiment`
    * [x] Class: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/experiment.py), [R](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a10/apis/r/R/SOMAExperiment.R)
      * Full parity except for `axis_query`
      * [ ] [R] Use `Futures` library to accelerate #943
    * [ ] `axis_query` -- convenience method on `SOMAExperiment` to create one [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/experiment.py#L54), [R] ... #736
    * [ ] `AxisQuery` class: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/query/axis.py#L50), [R] ... #736
  * `SOMAMeasurement`
    * [x] Class: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/measurement.py), [R](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a10/apis/r/R/SOMAMeasurement.R) -- full parity
  * Ephemeral -- more analysis pending until R's `ExperimentQuery` is merged
    * [ ] `uri`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/ephemeral/collections.py#L37), [R] #1022
    * [ ] `metadata`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/ephemeral/collections.py#L41), [R] #1022
    * [ ] `open`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/ephemeral/collections.py#L45), [R] #1022
    * [ ] `create`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/ephemeral/collections.py#L52), [R] #1022
    * [ ] `add_new_collection`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/ephemeral/collections.py#L57), [R] #938
    * [ ] `set`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/ephemeral/collections.py#L70), [R] #1022
* Options
  * [ ] Class: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/options.py), [R] ...
* To be filed
  * [ ] `coos`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L287), [R] #1007
  * [ ] `dense_tensors`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L296), [R] #1007
  * [ ] `record_batches`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L298), [R] #1007
  * [ ] `tables`: [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L301), [R] #1007
* To/from Seurat matching Python's [`soma.io`](https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a11/apis/python/src/tiledbsoma/io/ingest.py)
  * `to_seurat` #941 
  * `from_seurat` #941 
* Other
  * [ ] `nnz` when `allow_duplicates=True` #989 #990 #991
  * [ ] Appendability of `SparseNDArray` #931 #972

**Comment by johnkerl** [comment]
RFC checklist (_very_ much WIP)

* Not ready for micro-edits
* Feedback I'm looking for right now @aaronwolen is if this is the _kind_ of thing that would be most helpful and if so I can flesh this out more

```
* Foundational types
  * `SOMADataFrame`
    * [ ] `create`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L44)
      * [R] ...
    * [ ] `read`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L59)
      * [R] ...
    * [ ] `write`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L77)
      * [R] ...
    * [ ] `schema`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L93)
      * [R] ...
    * [ ] `index_column_names`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L99)
      * [R] ...
  * `NDArray` shared code
  * `SOMASparseNDArray`
    * [ ] `create`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L117)
      * [R] ...
    * [ ] `read`
      * read
    * [ ] `shape`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L133)
      * [R] ...
    * [ ] `nnz`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L243)
      * [R] ...
    * [ ] `ndim`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L138)
      * [R] ...
    * [ ] `schema`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L207)
      * [R] ...
    * [ ] `write`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L230)
      * [R] ...
  * `SOMADenseNDArray`
    * [ ] `read`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L160)
      * [R] ...
    * [ ] `shape`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L133)
      * [R] ...
    * [ ] `ndim`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L138)
      * [R] ...
    * [ ] `schema`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L144)
      * [R] ...
    * [ ] `write`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L176)
      * [R] ...
* Composed types
  * Shared code
    * [ ] `open`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/base.py#L24)
      * [R] ...
    * [ ] `uri`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/base.py#L37)
      * [R] ...
    * [ ] `context`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/base.py#L42)
      * [R] ...
    * [ ] `metadata`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/base.py#L57)
      * [R] ...
    * [ ] `close`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/base.py#L77)
      * [R] ...
  * `SOMACollection`
    * [ ] `create`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/collection.py#L31)
      * [R] ...
    * [ ] `add_new_collection`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/collection.py#L75)
      * [R] ...
    * [ ] `add_new_dataframe`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/collection.py#L124)
      * [R] ...
    * [ ] `add_new_dense_ndarray`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/collection.py#L141)
      * [R] ...
    * [ ] `add_new_sparse_ndarray`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/collection.py#L158)
      * [R] ...
    * [ ] `set`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/collection.py#L180)
      * [R] ...
  * `SOMAExperiment`
    * [ ] `axis_query`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/experiment.py#L54)
      * [R] ...
    * [ ] `wut`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/query/axis.py#L50)
      * [R] ...
  * `SOMAMeasurement`
    * [ ] `wut`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/measurement.py)
      * [R] ...
  * Ephemeral
    * [ ] `uri`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/ephemeral/collections.py#L37)
      * [R] ...
    * [ ] `metadata`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/ephemeral/collections.py#L41)
      * [R] ...
    * [ ] `open`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/ephemeral/collections.py#L45)
      * [R] ...
    * [ ] `create`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/ephemeral/collections.py#L52)
      * [R] ...
    * [ ] `add_new_collection`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/ephemeral/collections.py#L57)
      * [R] ...
    * [ ] `set`
      * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/ephemeral/collections.py#L70)
      * [R] ...
* Options
  * [ ] `wut`
    * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/options.py)
    * [R] ...
* TBF
  * [ ] `coos`
    * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L287)
    * [R] ...
  * [ ] `cscs`
    * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L289)
    * [R] ...
  * [ ] `csrs`
    * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L293)
    * [R] ...
  * [ ] `dense_tensors`
    * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L296)
    * [R] ...
  * [ ] `record_batches`
    * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L298)
    * [R] ...
  * [ ] `tables`
    * [spec](https://github.com/single-cell-data/SOMA/blob/python-v0.0.0a12/python-spec/src/somacore/data.py#L301)
    * [R] ...
```

**Comment by johnkerl** [comment]
It looks like a merge of #963 auto-closed this parent task; GH automation overstep 😁

**Comment by eddelbuettel** [comment]
My bad. I put the wrong ticket into the PR. Should have been #963, typed #863. Whoops.  Get me one of those 'do what I mean not do as I say' computers, please.

**Comment by johnkerl** [comment]
Everything here has been split out into separate tracking issues. Closing this issue.
