### ISSUE TITLE
[c++] C++ unification tracking (high-level/parent issue)

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#922]
Goal of having a single copy of tiledb core via `libtiledbsoma`, eliminating all use of `tiledb-py` and `tiledb-r`:

* Currently present in `SOMAReader` (as of 2023-02-13):
    * Arrays:
        * [x] `read` for arrays
            * supporting methods like `set_dim_points`, `submit`, `results_complete`, etc.
        * [x] `nnz`
    * [x] `stats` access
* Reads:
    * Arrays
        * [x] Rename `SOMAReader` to `SOMAArrayReader`
        * [ ] Optimize CSR I/O (for Python) or CSC I/O (for R): see also #718 
        * [x] `shape` #927
        * [ ] `schema` reads (as Arrow) #1121
        * [ ] `metadata` reads #926 
        * [ ] `open` (for read) and `close`
    * Groups:
        * [ ] Make a `SOMAGroupReader` #1122
        * [ ] `open` (for read), and `close`
        * [ ] Get member name-to-URI map #1122
* Writes:
    * Arrays:
        * [ ] Make a `SOMAArrayWriter`
        * [ ] `open` (for write), and `close`
        * [ ] update metadata
        * [ ] `write` bulk data
    * Groups:
        * [ ] Make a `SOMAGroupWriter` #1182
        * [ ] `create` #1182
        * [ ] `open` (for write), and `close`
        * [ ] add/delete members
        * [ ] update metadata

Query API:

* [ ] Port query logic to C++
  * The current query logic (in `somacore`) uses _only_ the API, with no direct implementation-level accesses.
  * This could almost all be translated into C++.
  * As pre-requisite work, we'll need `SOMAArrayReader` and `SOMAGroupReader` feature-complete (as building blocks) before we can implement this in C++
  * `SOMAArrayWriter` and `SOMAGroupWriter` development can proceed in parallel with this.

Feature completion:

* [ ] Let `SOMAReader` use all supported types (not just `int` and `string` as currently) to index `SOMADataFrame`
    * https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a11/libtiledbsoma/src/pyapi/libtiledbsoma.cc#L328-L350
 
Read performance, and in particular all of the zero-copy or ecosystem format paths (optmized CSC/CSR, etc)

* [ ] in principle, we should consider at a zero-copy path for any format that the user will want to use from R or Python.

Large out-of-core / distributed processing:

* [ ] Partitioning support

cc @gspowley @nguyenv @Shelnutt2 @eddelbuettel

**Comment by bkmartinjr** [comment]
See also #718 (and the R equivalent would be CSC reading)

**Comment by johnkerl** [comment]
Updated -- thanks @bkmartinjr !

**Comment by bkmartinjr** [comment]
Additional suggestion: there are multiple "themes" here that motivate the smaller items.  It would be helpful to identify those and group the small items by their epic/theme. I believe they are:
* Link in a single instance of TileDB core:  this is the write path, schema, meta, and other small stuff
* Read performance, and in particular all of the zero-copy or ecosystem format paths (optmized CSC/CSR, etc)
* Large out-of-core / distributed processing - the partitioning of reads

Organizing around these would make it simpler to discuss prioritization.

**Comment by johnkerl** [comment]
@bkmartinjr done as requested

**Comment by johnkerl** [comment]
It sounds like @nguyenv will be duping this out on #1240

**Comment by nguyenv** [comment]
Tracking has been transferred to https://github.com/single-cell-data/TileDB-SOMA/issues/1240.
